version: "3"
services:
  database:
    image: postgres:9.6-alpine
    container_name: book-reader-psql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

# now the DB is accessible via
# postgresql://postgres:postgres@localhost:5432/postgres
