enum BookLoanStartActionName {
  START_READ_ALL_BOOK_LOANS = 'bookLoan/START_READ_ALL_BOOK_LOANS',
  START_READ_ALL_BORROWED = 'bookLoan/START_READ_ALL_BORROWED',

  START_CREATE_BOOK_LOAN = 'bookLoan/START_CREATE_BOOK_LOAN',
  START_UPDATE_BOOK_LOAN = 'bookLoan/START_UPDATE_BOOK_LOAN',
  START_DELETE_BOOK_LOAN = 'bookLoan/START_DELETE_BOOK_LOAN',
}


enum BookLoanSucceededActionName {
  READ_ALL_BOOK_LOANS_SUCCEEDED = 'bookLoan/READ_ALL_BOOK_LOANS_SUCCEEDED',
  READ_ALL_BORROWED_SUCCEEDED = 'bookLoan/READ_ALL_BORROWED_SUCCEEDED',
}

export enum BookLoanSucceededWithMessageActionName {
  CREATE_BOOK_LOAN_SUCCEEDED = 'bookLoan/CREATE_BOOK_LOAN_SUCCEEDED',
  UPDATE_BOOK_LOAN_SUCCEEDED = 'bookLoan/UPDATE_BOOK_LOAN_SUCCEEDED',
  DELETE_BOOK_LOAN_SUCCEEDED = 'bookLoan/DELETE_BOOK_LOAN_SUCCEEDED',
}

export enum BookLoanFailedActionName {
  READ_ALL_BOOK_LOANS_FAILED = 'bookLoan/READ_ALL_BOOK_LOANS_FAILED',
  READ_ALL_BORROWED_FAILED = 'bookLoan/READ_ALL_BORROWED_FAILED',

  CREATE_BOOK_LOAN_FAILED = 'bookLoan/CREATE_BOOK_LOAN_FAILED',
  UPDATE_BOOK_LOAN_FAILED = 'bookLoan/UPDATE_BOOK_LOAN_FAILED',
  DELETE_BOOK_LOAN_FAILED = 'bookLoan/DELETE_BOOK_LOAN_FAILED',
}


export const BookLoanActionName = {
  ...BookLoanStartActionName,
  ...BookLoanSucceededWithMessageActionName,
  ...BookLoanSucceededActionName,
  ...BookLoanFailedActionName,
};
