enum LibraryStartActionName {
  START_GET_ALL_AUTHORS = 'bookData/START_GET_ALL_AUTHORS',
  START_GET_ALL_BOOKS = 'bookData/START_GET_ALL_BOOKS',
  START_GET_ALL_BOOK_DATA = 'bookData/START_GET_ALL_BOOK_DATA',
  START_GET_ALL_GENRES = 'bookData/START_GET_ALL_GENRES',
  START_GET_ALL_LABELS = 'bookData/START_GET_ALL_LABELS',
  START_GET_ALL_PERSONAL_BOOK_DATA = 'bookData/START_GET_ALL_PERSONAL_BOOK_DATA',
  START_GET_ALL_REVIEWS = 'bookData/START_GET_ALL_REVIEWS',

  START_GET_BOOK_DATA = 'bookData/START_GET_BOOK_DATA',

  START_UPDATE_BOOK_DATA = 'bookData/START_UPDATE_BOOK_DATA',
  START_DELETE_BOOK_DATA = 'bookData/START_DELETE_BOOK_DATA',
}

enum LibrarySucceededActionName {
  GET_ALL_AUTHORS_SUCCEEDED = 'bookData/GET_ALL_AUTHORS_SUCCEEDED',
  GET_ALL_BOOKS_SUCCEEDED = 'bookData/GET_ALL_BOOKS_SUCCEEDED',
  GET_ALL_GENRES_SUCCEEDED = 'bookData/GET_ALL_GENRES_SUCCEEDED',
  GET_ALL_BOOK_DATA_SUCCEEDED = 'bookData/GET_ALL_BOOK_DATA_SUCCEEDED',
  GET_ALL_LABELS_SUCCEEDED = 'bookData/GET_ALL_LABELS_SUCCEEDED',
  GET_ALL_PERSONAL_BOOK_DATA_SUCCEEDED = 'bookData/GET_ALL_PERSONAL_BOOK_DATA_SUCCEEDED',
  GET_ALL_REVIEWS_SUCCEEDED = 'bookData/GET_ALL_REVIEWS_SUCCEEDED',

  GET_BOOK_DATA_SUCCEEDED = 'bookData/GET_BOOK_DATA_SUCCEEDED',

  UPDATE_BOOK_DATA_SUCCEEDED = 'bookData/UPDATE_BOOK_DATA_SUCCEEDED',
  DELETE_BOOK_DATA_SUCCEEDED = 'bookData/DELETE_BOOK_DATA_SUCCEEDED',
}

export enum LibrarySucceededWithMessageActionName {
}

export enum LibraryFailedActionName {
  GET_ALL_AUTHORS_FAILED = 'bookData/GET_ALL_BOOK_DATA_FAILED',
  GET_ALL_BOOKS_FAILED = 'bookData/GET_ALL_BOOKS_FAILED',
  GET_ALL_GENRES_FAILED = 'bookData/GET_ALL_GENRES_FAILED',
  GET_ALL_BOOK_DATA_FAILED = 'bookData/GET_ALL_BOOK_DATA_FAILED',
  GET_ALL_LABELS_FAILED = 'bookData/GET_ALL_LABELS_FAILED',
  GET_ALL_PERSONAL_BOOK_DATA_FAILED = 'bookData/GET_ALL_PERSONAL_BOOK_DATA_FAILED',
  GET_ALL_REVIEWS_FAILED = 'bookData/GET_ALL_REVIEWS_FAILED',

  GET_BOOK_DATA_FAILED = 'bookData/GET_BOOK_DATA_FAILED',

  UPDATE_BOOK_DATA_FAILED = 'bookData/UPDATE_BOOK_DATA_FAILED',
  DELETE_BOOK_DATA_FAILED = 'bookData/DELETE_BOOK_DATA_FAILED',
}

export const LibraryActionName = {
  ...LibraryStartActionName,
  ...LibrarySucceededWithMessageActionName,
  ...LibrarySucceededActionName,
  ...LibraryFailedActionName,
};
