enum LibraryStartActionName {
  START_GET_ALL_AUTHORS = 'library/START_GET_ALL_AUTHORS',
  START_GET_ALL_BOOKS = 'library/START_GET_ALL_BOOKS',
  START_GET_ALL_BOOK_DATA = 'library/START_GET_ALL_BOOK_DATA',
  START_GET_ALL_GENRES = 'library/START_GET_ALL_GENRES',
  START_GET_ALL_LABELS = 'library/START_GET_ALL_LABELS',
  START_GET_ALL_PERSONAL_BOOK_DATA = 'library/START_GET_ALL_PERSONAL_BOOK_DATA',
  START_GET_ALL_REVIEWS = 'library/START_GET_ALL_REVIEWS',

  START_GET_BOOK_DATA = 'library/START_GET_BOOK_DATA',

  START_CREATE_BOOK_DATA = 'library/START_CREATE_BOOK_DATA',
  START_UPDATE_BOOK_DATA = 'library/START_UPDATE_BOOK_DATA',
  START_DELETE_BOOK_DATA = 'library/START_DELETE_BOOK_DATA',

  START_CREATE_LABEL = 'library/START_CREATE_LABEL',
  START_UPDATE_LABEL = 'library/START_UPDATE_LABEL',
  START_DELETE_LABEL = 'library/START_DELETE_LABEL',
}

enum LibrarySucceededActionName {
  GET_ALL_AUTHORS_SUCCEEDED = 'library/GET_ALL_AUTHORS_SUCCEEDED',
  GET_ALL_BOOKS_SUCCEEDED = 'library/GET_ALL_BOOKS_SUCCEEDED',
  GET_ALL_GENRES_SUCCEEDED = 'library/GET_ALL_GENRES_SUCCEEDED',
  GET_ALL_BOOK_DATA_SUCCEEDED = 'library/GET_ALL_BOOK_DATA_SUCCEEDED',
  GET_ALL_LABELS_SUCCEEDED = 'library/GET_ALL_LABELS_SUCCEEDED',
  GET_ALL_PERSONAL_BOOK_DATA_SUCCEEDED = 'library/GET_ALL_PERSONAL_BOOK_DATA_SUCCEEDED',
  GET_ALL_REVIEWS_SUCCEEDED = 'library/GET_ALL_REVIEWS_SUCCEEDED',

  GET_BOOK_DATA_SUCCEEDED = 'library/GET_BOOK_DATA_SUCCEEDED',
}

export enum LibrarySucceededWithMessageActionName {
  CREATE_BOOK_DATA_SUCCEEDED = 'library/CREATE_BOOK_DATA_SUCCEEDED',
  UPDATE_BOOK_DATA_SUCCEEDED = 'library/UPDATE_BOOK_DATA_SUCCEEDED',
  DELETE_BOOK_DATA_SUCCEEDED = 'library/DELETE_BOOK_DATA_SUCCEEDED',

  CREATE_LABEL_SUCCEEDED = 'library/CREATE_LABEL_SUCCEEDED',
  UPDATE_LABEL_SUCCEEDED = 'library/UPDATE_LABEL_SUCCEEDED',
  DELETE_LABEL_SUCCEEDED = 'library/DELETE_LABEL_SUCCEEDED',
}

export enum LibraryFailedActionName {
  GET_ALL_AUTHORS_FAILED = 'library/GET_ALL_BOOK_DATA_FAILED',
  GET_ALL_BOOKS_FAILED = 'library/GET_ALL_BOOKS_FAILED',
  GET_ALL_GENRES_FAILED = 'library/GET_ALL_GENRES_FAILED',
  GET_ALL_BOOK_DATA_FAILED = 'library/GET_ALL_BOOK_DATA_FAILED',
  GET_ALL_LABELS_FAILED = 'library/GET_ALL_LABELS_FAILED',
  GET_ALL_PERSONAL_BOOK_DATA_FAILED = 'library/GET_ALL_PERSONAL_BOOK_DATA_FAILED',
  GET_ALL_REVIEWS_FAILED = 'library/GET_ALL_REVIEWS_FAILED',

  GET_BOOK_DATA_FAILED = 'library/GET_BOOK_DATA_FAILED',

  CREATE_BOOK_DATA_FAILED = 'library/CREATE_BOOK_DATA_FAILED',
  UPDATE_BOOK_DATA_FAILED = 'library/UPDATE_BOOK_DATA_FAILED',
  DELETE_BOOK_DATA_FAILED = 'library/DELETE_BOOK_DATA_FAILED',

  CREATE_LABEL_FAILED = 'library/CREATE_LABEL_FAILED',
  UPDATE_LABEL_FAILED = 'library/UPDATE_LABEL_FAILED',
  DELETE_LABEL_FAILED = 'library/DELETE_LABEL_FAILED',
}

export const LibraryActionName = {
  ...LibraryStartActionName,
  ...LibrarySucceededWithMessageActionName,
  ...LibrarySucceededActionName,
  ...LibraryFailedActionName,
};
