enum WishlistStartActionName {
  START_READ_WISHLIST = 'wishlist/START_READ_WISHLIST',
  START_READ_ALL_BOOKED_BOOK_REQUESTS = 'wishlist/START_READ_ALL_BOOKED_BOOK_REQUESTS',

  START_CREATE_BOOK_REQUEST = 'wishlist/START_CREATE_BOOK_REQUEST',
  START_BOOK_BOOK_REQUEST = 'wishlist/START_BOOK_BOOK_REQUEST',
  START_UPDATE_BOOK_REQUEST = 'wishlist/START_UPDATE_BOOK_REQUEST',
  START_DELETE_BOOK_REQUEST = 'wishlist/START_DELETE_BOOK_REQUEST',

  START_MOVE_BOOK_TO_LIBRARY = 'wishlist/START_MOVE_BOOK_TO_LIBRARY',
}

enum WishlistSucceededActionName {
  READ_WISHLIST_SUCCEEDED = 'wishlist/READ_WISHLIST_SUCCEEDED',
  READ_ALL_BOOKED_BOOK_REQUESTS_SUCCEEDED = 'wishlist/READ_ALL_BOOKED_BOOK_REQUESTS_SUCCEEDED',
}

export enum WishlistSucceededWithMessageActionName {
  CREATE_BOOK_REQUEST_SUCCEEDED = 'wishlist/CREATE_BOOK_REQUEST_SUCCEEDED',
  BOOK_BOOK_REQUEST_SUCCEEDED = 'wishlist/BOOK_BOOK_REQUEST_SUCCEEDED',
  UPDATE_BOOK_REQUEST_SUCCEEDED = 'wishlist/UPDATE_BOOK_REQUEST_SUCCEEDED',
  DELETE_BOOK_REQUEST_SUCCEEDED = 'wishlist/DELETE_BOOK_REQUEST_SUCCEEDED',

  MOVE_BOOK_TO_LIBRARY_SUCCEEDED = 'wishlist/MOVE_BOOK_TO_LIBRARY_SUCCEEDED',
}

export enum WishlistFailedActionName {
  READ_WISHLIST_FAILED = 'wishlist/READ_WISHLIST_FAILED',
  READ_ALL_BOOKED_BOOK_REQUESTS_FAILED = 'wishlist/READ_ALL_BOOKED_BOOK_REQUESTS_FAILED',

  CREATE_BOOK_REQUEST_FAILED = 'wishlist/CREATE_BOOK_REQUEST_FAILED',
  BOOK_BOOK_REQUEST_FAILED = 'wishlist/BOOK_BOOK_REQUEST_FAILED',
  UPDATE_BOOK_REQUEST_FAILED = 'wishlist/UPDATE_BOOK_REQUEST_FAILED',
  DELETE_BOOK_REQUEST_FAILED = 'wishlist/DELETE_BOOK_REQUEST_FAILED',

  MOVE_BOOK_TO_LIBRARY_FAILED = 'wishlist/MOVE_BOOK_TO_LIBRARY_FAILED',
}

export const WishlistActionName = {
  ...WishlistStartActionName,
  ...WishlistSucceededWithMessageActionName,
  ...WishlistSucceededActionName,
  ...WishlistFailedActionName,
};
