enum WishlistStartActionName {
  START_GET_WISHLIST = 'wishlist/START_GET_WISHLIST',
  START_GET_ALL_BOOKED_BOOK_REQUESTS = 'wishlist/START_GET_ALL_BOOKED_BOOK_REQUESTS',

  START_CREATE_BOOK_REQUEST = 'wishlist/START_CREATE_BOOK_REQUEST',
  START_UPDATE_BOOK_REQUEST = 'wishlist/START_UPDATE_BOOK_REQUEST',
  START_DELETE_BOOK_REQUEST = 'wishlist/START_DELETE_BOOK_REQUEST',
}

enum WishlistSucceededActionName {
  GET_WISHLIST_SUCCEEDED = 'wishlist/GET_WISHLIST_SUCCEEDED',
  GET_ALL_BOOKED_BOOK_REQUESTS_SUCCEEDED = 'wishlist/GET_ALL_BOOKED_BOOK_REQUESTS_SUCCEEDED',
}

export enum WishlistSucceededWithMessageActionName {
  CREATE_BOOK_REQUEST_SUCCEEDED = 'wishlist/CREATE_BOOK_REQUEST_SUCCEEDED',
  UPDATE_BOOK_REQUEST_SUCCEEDED = 'wishlist/UPDATE_BOOK_REQUEST_SUCCEEDED',
  DELETE_BOOK_REQUEST_SUCCEEDED = 'wishlist/DELETE_BOOK_REQUEST_SUCCEEDED',
}

export enum WishlistFailedActionName {
  GET_WISHLIST_FAILED = 'wishlist/GET_WISHLIST_FAILED',
  GET_ALL_BOOKED_BOOK_REQUESTS_FAILED = 'wishlist/GET_ALL_BOOKED_BOOK_REQUESTS_FAILED',

  CREATE_BOOK_REQUEST_FAILED = 'wishlist/CREATE_BOOK_REQUEST_FAILED',
  UPDATE_BOOK_REQUEST_FAILED = 'wishlist/UPDATE_BOOK_REQUEST_FAILED',
  DELETE_BOOK_REQUEST_FAILED = 'wishlist/DELETE_BOOK_REQUEST_FAILED',
}

export const WishlistActionName = {
  ...WishlistStartActionName,
  ...WishlistSucceededWithMessageActionName,
  ...WishlistSucceededActionName,
  ...WishlistFailedActionName,
};
