export enum LoginActionName {
  START_LOGIN = 'login/START_LOGIN',
  LOGIN_SUCCEEDED = 'login/LOGIN_SUCCEEDED',
  LOGIN_FAILED = 'login/LOGIN_FAILED',

  START_REGISTRATION = 'login/START_REGISTRATION',
  REGISTRATION_FAILED = 'login/REGISTRATION_FAILED',
  REGISTRATION_SUCCEEDED = 'login/REGISTRATION_SUCCEEDED',

  LOGOUT = 'login/LOGOUT',
}
