export enum UserActionName {
  START_GET_CURRENT_USER = 'user/START_GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCEEDED = 'user/START_GET_CURRENT_USER_SUCCEEDED',
  GET_CURRENT_USER_FAILED = 'user/START_GET_CURRENT_USER_FAILED',

  START_GET_PUBLIC_USERS = 'user/START_GET_PUBLIC_USERS',
  GET_PUBLIC_USERS_SUCCEEDED = 'user/START_GET_PUBLIC_USERS_SUCCEEDED',
  GET_PUBLIC_USERS_FAILED = 'user/START_GET_PUBLIC_USERS_FAILED',
}
