export enum Path {
  author = 'author',
  book = 'book',
  bookData = 'book-data',
  bookRequest = 'book-request',
  borrowed = 'borrowed',
  friendship = 'friendship',
  genre = 'genre',
  hasLabel = 'has-label',
  label = 'label',
  login = 'login',
  personalBookData = 'personal-book-data',
  review = 'review',
  user = 'user',
}
