export enum RepositoryName {
  author = 'Author',
  bookData = 'BookData',
  book = 'Book',
  bookRequest = 'BookRequest',
  borrowed = 'Borrowed',
  friendship = 'Friendship',
  genre = 'Genre',
  hasLabel = 'HasLabel',
  label = 'Label',
  login = 'Login',
  personalBookData = 'PersonalBookData',
  review = 'Review',
  user = 'User',
}
